### ISSUE TITLE
benchmarks broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/benchmarks#10]
The benchmarks on c3potato are broken.

**Comment by orbeckst** [comment]
```
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py2.7-Cython0.27-mdanalysistests-numpy-scipy
·· Installing into conda-py2.7-Cython0.27-mdanalysistests-numpy-scipy
·· Error running ~/repositories/mdanalysis/benchmarks/env/491757a14a3783160c2e9816e3ecb44c/bin/python ~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py discover ~/repositories/mdanalysis/benchmarks/benchmarks /tmp/tmpggbgmixo/result.json
             STDOUT -------->

             STDERR -------->
             Traceback (most recent call last):
               File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py", line 867, in <module>
                 commands[mode](args)
               File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py", line 812, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py", line 797, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py", line 696, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py", line 648, in disc_files
                 module = import_module(package + filename)
               File "~/repositories/mdanalysis/benchmarks/env/491757a14a3783160c2e9816e3ecb44c/lib/python2.7/importlib/__init__.py", line 37, in import_module
                 __import__(name)
               File "~/repositories/mdanalysis/benchmarks/benchmarks/ag_methods.py", line 327, in <module>
                 class FragmentFinding(object):
               File "~/repositories/mdanalysis/benchmarks/benchmarks/ag_methods.py", line 330, in FragmentFinding
                 (PSF, DCD),  # single large fragment
             NameError: name 'PSF' is not defined
Traceback (most recent call last):
  File "~/miniconda3/envs/benchmark/bin/asv", line 11, in <module>
    load_entry_point('asv==0.3.dev1263+e1903152', 'console_scripts', 'asv')()
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/main.py", line 38, in main
    result = args.func(args)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/commands/run.py", line 132, in run_from_conf_args
    **kwargs
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/commands/run.py", line 192, in run
    commit_hashes, regex=bench)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmarks.py", line 396, in discover
    benchmarks = cls._disc_benchmarks(conf, repo, environments, commit_hash)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmarks.py", line 446, in _disc_benchmarks
    dots=False)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/plugins/conda.py", line 200, in run
    return self.run_executable('python', args, **kwargs)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/plugins/conda.py", line 206, in run_executable
    return super(Conda, self).run_executable(executable, args, **kwargs)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/environment.py", line 578, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/util.py", line 596, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '~/repositories/mdanalysis/benchmarks/env/491757a14a3783160c2e9816e3ecb44c/bin/python ~/miniconda3/envs/benchmark/lib/python3.6/site-packages/asv/benchmark.py discover ~/repositories/mdanalysis/benchmarks/benchmarks /tmp/tmpggbgmixo/result.json' returned non-zero exit status 1
```

**Comment by orbeckst** [comment]
Getting fixed with PR https://github.com/MDAnalysis/mdanalysis/pull/2260.

I am running the benchmarks manually but it will probably take a few days for them to catch up with the backlog from August 2018. The automatic benchmarks (nightly cron) are *disabled* until the manual one finishes.

**Comment by orbeckst** [comment]
Working again. The manual catch-up run took 4 days or so.
